# Generated by Django 4.1.6 on 2023-04-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='lesson_day',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
