# Generated by Django 4.1.6 on 2023-04-16 22:00

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_students_email_alter_students_lesson_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
